export const sortedTopics = [
  "Accidents",
  "Actors",
  "Advice",
  "Advertising",
  "Airplanes",
  "Airports",
  "Aliens",
  "Alcohol",
  "Animals",
  "Anti-Aging Creams",
  "Apartments",
  "Art",
  "Autumn",
  "Avatars",
  "Babysitting",
  "Bad Habits",
  "Banks",
  "Baths",
  "Beauty",
  "Being Afraid",
  "Being Married",
  "Being Single",
  "Birthdays",
  "Blood",
  "Books",
  "Bullying",
  "Business",
  "Busy",
  "Calories",
  "Carbon Footprint",
  "Careers",
  "Cars",
  "Cats",
  "Chickens",
  "Children",
  "Christmas",
  "Chocolate",
  "Climate Change",
  "Clothes",
  "Coffee",
  "Computers",
  "Cosmetic Surgery",
  "Cosmetics",
  "Credit Cards",
  "Crime",
  "Culture",
  "Current Events",
  "Cyber-bullying",
  "Cyber Crime",
  "Dancing",
  "Danger",
  "Death",
  "Dentists",
  "Diamonds",
  "Digital Cameras",
  "Directions",
  "Disability",
  "Discrimination",
  "Diseases",
  "Doctors",
  "Dogs",
  "Driving",
  "Drugs",
  "E-Mail",
  "Eating",
  "Education",
  "Eggs",
  "Electricity",
  "Emergencies",
  "Energy",
  "English",
  "Evolution",
  "Exercise",
  "Factory",
  "Famine",
  "Family",
  "Fashion",
  "Fast Food",
  "Fear",
  "Feet",
  "Fish",
  "Fishing",
  "Flowers",
  "Flying",
  "Food",
  "Food Safety",
  "Football",
  "Formula One",
  "Four Seasons",
  "Freedom",
  "French Fries",
  "Friends",
  "Frustration",
  "Fun",
  "Funerals",
  "Furniture",
  "Gambling",
  "Gangsters",
  "Gangs",
  "Gardening",
  "Gardens",
  "Genetic Engineering",
  "Genocide",
  "Getting Married",
  "Global Warming",
  "Globalization",
  "God",
  "Golden Week",
  "Google",
  "Gossip",
  "Grammar",
  "Gun Control",
  "Guns",
  "Hair",
  "Haircuts",
  "Halloween",
  "Hangovers",
  "Happiness",
  "Harry Potter",
  "Hate Crimes",
  "Health",
  "Healthcare",
  "Heart",
  "Heart Attacks",
  "Heaven",
  "Heroes",
  "Hiking",
  "Hip-Hop",
  "History",
  "Holidays",
  "Home School",
  "Homelessness",
  "Homes",
  "Horoscopes",
  "Hospitals",
  "Housewives",
  "Houses",
  "Human Rights",
  "Humour",
  "I Love You",
  "Identity Cards",
  "Immigration",
  "Inflation",
  "Information",
  "Insects",
  "Intelligence",
  "Internet",
  "Investments",
  "Job Interviews",
  "Jokes",
  "Journalism",
  "Juice",
  "Junk Mail",
  "Kissing",
  "Knowledge",
  "Language",
  "Laughter",
  "Laws",
  "Leadership",
  "Learning",
  "Libraries",
  "Lies",
  "Life",
  "Lifestyle",
  "Listening",
  "Literature",
  "Love",
  "Love at First Sight",
  "Luck",
  "Magazines",
  "Management",
  "Marathons",
  "Marketing",
  "Marriage",
  "Mathematics",
  "Meat",
  "Media",
  "Medicine",
  "Meditation",
  "Memories",
  "Men",
  "Mental Health",
  "Microsoft",
  "Milk",
  "Mobile Phones",
  "Models",
  "Modern Living",
  "Monarchy",
  "Money",
  "Moon",
  "Mothers",
  "Mountains",
  "Movies",
  "MP3s",
  "Multiculturalism",
  "Murder",
  "Museums",
  "Music",
  "Musical Instruments",
  "Mysteries",
  "Nails",
  "Names",
  "National Anthems",
  "Nationality",
  "Natural Disasters",
  "Neighbours",
  "News",
  "Night",
  "No",
  "Nobel Prize",
  "Noise",
  "Noses",
  "Numbers",
  "Nuclear Energy",
  "Nuclear Weapons",
  "Nursing",
  "Obesity",
  "Oceans",
  "Oil",
  "OK",
  "Olympics",
  "One",
  "Operations",
  "Opinions",
  "Organ Transplants",
  "Overpopulation",
  "Ozone Layer",
  "Painting",
  "Panic",
  "Parenting",
  "Parks",
  "Parties",
  "Passports",
  "Pasta",
  "Patience",
  "Peace",
  "People",
  "Perfume",
  "Personal Problems",
  "Personality",
  "Pets",
  "Philosophy",
  "Phobias",
  "Photography",
  "Physics",
  "Picnics",
  "Pilots",
  "Pizza",
  "Planets",
  "Plastic",
  "Plagiarism",
  "Police",
  "Politics",
  "Pollution",
  "Population",
  "Pornography",
  "Postal Service",
  "Potatoes",
  "Poverty",
  "Power",
  "Prayer",
  "Pregnancy",
  "Prejudice",
  "Prices",
  "Pride",
  "Privacy",
  "Pronunciation",
  "Property",
  "Prostitution",
  "Protests",
  "Psychology",
  "Public Relations",
  "Pubs, Clubs and Bars",
  "Pyramids",
  "Qualifications",
  "Quality",
  "Quality of Life",
  "Quarreling",
  "Questions",
  "Quizzes",
  "Quotations",
  "Racism",
  "Radio",
  "Radios",
  "Rain",
  "Ramadan",
  "Rap Music",
  "Reading",
  "Reality TV",
  "Red",
  "Refugees",
  "Religion",
  "Rent",
  "Research",
  "Restaurants",
  "Retirement",
  "Rice",
  "Risk",
  "Road Rage",
  "Robots",
  "Rock 'n' Roll",
  "Roses",
  "Royal Wedding",
  "Rubbish",
  "Rudeness",
  "Safety",
  "Salad",
  "Sand",
  "School",
  "Science",
  "Science Fiction",
  "Search Engines",
  "Security",
  "Senility",
  "Senses",
  "Sex",
  "Sexism",
  "Shopping",
  "Sightseeing",
  "Sin",
  "Skin",
  "Slavery",
  "Sleep",
  "Smelling",
  "Smiling",
  "Smoking",
  "Snow",
  "Social Issues",
  "Social Networking",
  "Social Work",
  "Socialism",
  "Society",
  "Software",
  "Solar Energy",
  "Solar System",
  "Soldiers",
  "Sound",
  "Souvenirs",
  "Speaking Activities",
  "Speed",
  "Spelling",
  "Spelling Activities",
  "Spiders",
  "Sport",
  "Spring",
  "Standard of Living",
  "Statistics",
  "Stem Cell Research",
  "Stereotypes",
  "Stock Market",
  "Stress",
  "Students",
  "Studying",
  "Success",
  "Sugar",
  "Suicide",
  "Summer",
  "Sumo",
  "Sun",
  "Super Bowl XLIV",
  "Supermarkets",
  "Surgery",
  "Sustainable Development",
  "Sweatshops",
  "Taxis",
  "Tax",
  "Tears",
  "Teaching",
  "Technology",
  "Teddy Bears",
  "Teenagers",
  "Teeth",
  "Telephones",
  "Television",
  "Temperature",
  "Tennis",
  "Terrorism",
  "The Family Pet",
  "Theatre",
  "Time",
  "Tigers",
  "Tourism",
  "Toys",
  "Traffic",
  "Trains",
  "Translation",
  "Transplants",
  "Travelling",
  "UFOs",
  "United Nations",
  "Universe",
  "Vegetarianism",
  "Video Games",
  "Violence",
  "Vocabulary",
  "Vocabulary Activities",
  "Volunteerism",
  "Voting",
  "Walking",
  "War",
  "War Crimes",
  "Water",
  "Weapons",
  "Weather",
  "Websites",
  "Wedding Anniversaries",
  "Weddings",
  "Weekends",
  "Weight",
  "Whales",
  "Winter",
  "Winter Olympics",
  "Women",
  "Words",
  "Writing",
  "Writing Activities",
  "Xenophobia",
  "X-Rays",
  "Yes",
  "Youth",
  "Zoos",
];
